# Generated by Django 2.1.15 on 2020-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(default='', upload_to='E_Commerce/HomeSlider'),
        ),
    ]
