# Generated by Django 2.1.15 on 2020-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0003_topproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikeprice', models.IntegerField(default='', max_length=10)),
                ('price', models.IntegerField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
                ('top_prod_image', models.ImageField(default='', upload_to='E_Commerce/TopProducts')),
            ],
        ),
    ]
