# Generated by Django 2.1.15 on 2020-08-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0005_prodcards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdCards',
            new_name='ProdCard',
        ),
    ]
