# Generated by Django 2.1.15 on 2020-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0007_productcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCard',
        ),
    ]
