# Generated by Django 2.1.15 on 2020-08-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0008_delete_productcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcard',
            name='cardImage',
            field=models.ImageField(default='', height_field='200', upload_to='E_Commerce/Cards', width_field='100'),
        ),
    ]
