# Generated by Django 2.1.15 on 2020-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0009_auto_20200819_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcard',
            name='cardImage',
            field=models.ImageField(default='', upload_to='E_Commerce/Cards'),
        ),
    ]
