# Generated by Django 2.1.15 on 2020-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0010_auto_20200819_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcard',
            name='carddesc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
