# Generated by Django 3.1 on 2020-08-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0012_menproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menproducts',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='menproducts',
            name='strikeprice',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='strikeprice',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='trendingproducts',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='trendingproducts',
            name='strikeprice',
            field=models.IntegerField(default=''),
        ),
    ]
