# Generated by Django 3.1 on 2020-08-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0014_cussignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cussignup',
            old_name='UserFirstName',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='cussignup',
            name='UserLastName',
        ),
    ]
