# Generated by Django 3.1 on 2020-08-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0015_auto_20200822_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusSignUp',
            new_name='CustomerSignUp',
        ),
    ]
