# Generated by Django 3.1 on 2020-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0016_auto_20200822_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikeprice', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=20)),
                ('men_prod_image', models.ImageField(default='', upload_to='E_Commerce/TopProducts')),
            ],
        ),
    ]
