# Generated by Django 3.1 on 2020-08-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0018_auto_20200824_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialoffers',
            old_name='men_prod_image',
            new_name='special_prod_image',
        ),
    ]
