# Generated by Django 3.1 on 2020-08-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0020_auto_20200824_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffers',
            name='arrives',
            field=models.DateField(verbose_name=datetime.date(2020, 8, 24)),
        ),
    ]
