# Generated by Django 3.1 on 2020-08-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0022_auto_20200824_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffers',
            name='birthdate',
        ),
    ]
