# Generated by Django 3.1 on 2020-08-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0023_remove_specialoffers_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffers',
            name='arrives',
        ),
        migrations.RemoveField(
            model_name='specialoffers',
            name='description',
        ),
    ]
