# Generated by Django 3.1 on 2020-08-24 11:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0025_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='specialoffers',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2020, 8, 24, 4, 52, 26, 293936)),
            preserve_default=False,
        ),
    ]
