# Generated by Django 3.1 on 2020-08-24 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0030_auto_20200824_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffers',
            name='date',
            field=models.DateField(default='', verbose_name=datetime.datetime(2020, 8, 24, 4, 54, 43, 530331)),
        ),
    ]
