# Generated by Django 3.1 on 2020-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0031_auto_20200824_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffers',
            name='date',
        ),
        migrations.AddField(
            model_name='specialoffers',
            name='name2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
