# Generated by Django 3.1 on 2020-08-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0032_auto_20200824_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffers',
            name='name2',
        ),
    ]
