# Generated by Django 3.1 on 2020-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0033_remove_specialoffers_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='arrives',
            field=models.CharField(default='', max_length=10),
        ),
    ]
